# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee41201879926cb3f06e1a0a1e6804de766b4c0ae4a508ba24cb901d7f4e5bae549bcf80760c58f269f1cba49220a49cf8daecf47adc8bbe6eb00c3bf6eaac9d

test:
  secret_key_base: 4fb3f11c904e67aeebb816f1d03ac8b491548caca9f4cafd5da507722c69a1203ac1eee1d912ed7382e81db24ea883b25f4a81bf64449ae48260addcf30cf88b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
